version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: dalyleide/reverseproxy:v1
  backend_user:
    build:
      context: ./udagram-api-user-02
    image: dalyleide/udagram-api-user-02:v1
  backend_feed:
    build:
      context: ./udagram-api-feed-02
    image: dalyleide/udagram-api-feed-02:v1
  frontend:
    build:
      context: ./udagram-frontend
    image: dalyleide/udagram-frontend:v1
