version: '3.4'
services:
  db:
    image: dalyleide/mysql-service-api-voting
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: api_voting
    ports:
      - "3308:3306"
    networks: 
      - api-voting-network
  service-api-voting:
    image: dalyleide/service-api-voting
    restart: always
    build: ./api-voting
    working_dir: /api-voting
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    volumes:
      - ./api-voting:/api-voting
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks: 
      - api-voting-network
networks:
    api-voting-network:
        driver: bridge